/// Configuration rules for the ChiGlow Energy Engine.
///
/// This file defines the business rules that the EnergyEngine uses to
/// calculate Five Element balance and Bagua life area scores.
///
/// ## Why separate config?
/// The engine (`energy_engine.dart`) is pure calculation logic — it reads
/// rules from here and processes inputs. Changing weights, adding new
/// life areas, or adjusting cycle relationships never requires touching
/// the engine itself.
///
/// ## How to modify
/// - Element weights: adjust the `weight` values within each Bagua rule.
///   They must sum to 1.0 per area.
/// - Element cycles: `generatingCycle` and `controllingCycle` define the
///   Five Element relationships. These rarely change.
/// - Element indices: 0=Wood, 1=Fire, 2=Earth, 3=Metal, 4=Water
class EnergyConfig {
  // ── Element Reference ──
  static const elementLabels = ['Wood', 'Fire', 'Earth', 'Metal', 'Water'];

  static const elementEmojis = {
    'Wood': '🌿',
    'Fire': '🔥',
    'Earth': '🌍',
    'Metal': '⚔️',
    'Water': '💧',
  };

  // ── Five Element Cycles ──

  /// Generating (Sheng) cycle: Wood → Fire → Earth → Metal → Water → Wood
  /// Each element generates the next element in the cycle.
  /// Element at index i generates element at index (i + 1) % 5.
  static const generatingCycle = [1, 2, 3, 4, 0]; // what each element generates

  /// Controlling (Ke) cycle: Wood → Earth → Water → Fire → Metal → Wood
  /// Each element controls the element two steps ahead.
  /// Element at index i controls element at index (i + 2) % 5.
  static const controllingCycle = [2, 3, 4, 0, 1]; // what each element controls

  // ── Zodiac → Primary Element ──
  static const zodiacElement = <String, int>{
    'Rat': 4, 'Ox': 2, 'Tiger': 0, 'Rabbit': 0,
    'Dragon': 2, 'Snake': 1, 'Horse': 1, 'Goat': 2,
    'Monkey': 3, 'Rooster': 3, 'Dog': 2, 'Pig': 4,
  };

  // ── Year Energy ──

  /// Heavenly Stem element index by year % 10.
  /// 0-1→Metal, 2-3→Water, 4-5→Wood, 6-7→Fire, 8-9→Earth
  static const stemElement = [3, 3, 4, 4, 0, 0, 1, 1, 2, 2];

  // ── Element Balance Scoring ──

  /// Base score adjustments for the Five Element balance calculation.
  /// These values are added to the neutral base (50) for each element
  /// based on its relationship to the user's zodiac primary element.
  static const elementBalanceScoring = {
    'primaryElement': 25,
    'parentElement': 10,   // generates the primary
    'childElement': 5,     // generated by the primary
    'controllingElement': -10, // controls the primary
    'controlledElement': -5,  // controlled by the primary
  };

  /// Year energy modulation values.
  static const yearEnergyScoring = {
    'sameElement': 12,
    'nurturedElement': 6,  // year's element generates this element
    'feedingElement': 4,   // this element generates the year's element
  };

  // ── Bagua Life Area Rules ──

  /// Scoring rules for each Bagua life area.
  ///
  /// Each rule defines:
  /// - `primary`: the primary element name
  /// - `primaryWeight`: weight of the primary element (0.0–1.0)
  /// - `supporting`: map of supporting element names to their weights
  ///
  /// Special supporting element names:
  /// - `'OverallHarmony'`: average of all 5 element scores
  ///
  /// All weights for an area must sum to 1.0.
  static const baguaRules = {
    'Love': {
      'primary': 'Earth',
      'primaryWeight': 0.50,
      'supporting': {
        'Fire': 0.25,  // generates Earth
        'Metal': 0.25, // Earth generates Metal
      },
    },
    'Wealth': {
      'primary': 'Wood',
      'primaryWeight': 0.50,
      'supporting': {
        'Water': 0.25, // generates Wood
        'Fire': 0.25,  // Wood generates Fire
      },
    },
    'Health': {
      'primary': 'Earth',
      'primaryWeight': 0.40,
      'supporting': {
        'OverallHarmony': 0.60, // average of all 5 elements
      },
    },
    'Career': {
      'primary': 'Water',
      'primaryWeight': 0.50,
      'supporting': {
        'Metal': 0.25, // generates Water
        'Wood': 0.25,  // Water generates Wood
      },
    },
  };

  // ── Room Scan Blend ──

  /// Maximum influence room scans can have on the elemental balance.
  /// 0.4 = 40% max influence after many scans.
  static const double roomScanMaxBlend = 0.4;

  /// How much each additional scan increases the blend weight.
  /// 0.05 = 5% per scan, reaching max at ~8 scans.
  static const double roomScanBlendPerScan = 0.05;
}